# Generated by Django 6.0.3 on 2026-04-05 09:36

import django.db.models.deletion
import tracker.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlasticSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plastic_type', models.CharField(choices=[('bottle', 'Plastic Bottle'), ('bag', 'Plastic Bag'), ('container', 'Plastic Container'), ('packaging', 'Plastic Packaging'), ('other', 'Other Plastic')], max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('points_earned', models.IntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='PrizeRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize_id', models.CharField(max_length=20)),
                ('prize_name', models.CharField(max_length=100)),
                ('points_spent', models.IntegerField()),
                ('code', models.CharField(default=tracker.models.generate_code, max_length=20, unique=True)),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-redeemed_at'],
            },
        ),
        migrations.DeleteModel(
            name='RecyclingEntry',
        ),
    ]
